disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- identifier_name
- line_length
- force_cast
- force_try

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

