# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

use_frameworks!

workspace 'App'

target 'Rawgar-SwiftUI' do

  # Pods for Rawgar-SwiftUI
  pod 'RealmSwift'
  pod 'Alamofire'
  pod 'SDWebImageSwiftUI'
  pod 'SwiftLint'
  pod 'Core', :git =>'https://github.com/reyhanraz/Rawgar-Core.git'

end

target 'Game' do
  project '../Modul/Game/Game'

  pod 'RealmSwift'
  pod 'Alamofire'
  pod 'Core', :git =>'https://github.com/reyhanraz/Rawgar-Core.git'

end